---
from: didier.banlock@gmail.com
domain: safe-match-squash.herokuapp.com
strategy: smtp
smtp_settings:
  address: google.com
  port: '25'
  domain: safe-match-squash.herokuapp.com
  user_name: didier.banlock@gmail.com
  password: "@WIlson.1+"
  authentication: plain
  enable_starttls_auto: false
